language: generic

env:
  global:
    - PROJECT_NAME=pypolyline
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - secure: jDdzqlgtXOlnXgL3VYCjtgYAZj2RkPGKyOgzCPtdPt6xdWjN3f3l0tcMBR304FYXTLgJkEkQcRFkB2ykaNwhkLEtHC6+4VmSv9aP9SC9NpG6i9go/cKIHSlLpCifV0ggQla6TV2rHi8owe9Qv1q5OIjqtvEcixexpCEHmSyIIoISPxuAcNIylp5XiL6dVgwk1qwlrmsCWhY9pxPxnUOf3di7TQNxOxNNR4qJHVdbomXOsQEjOZVh5AbVMqiGzrBje2dTEZrADr+L9ZeGiHGU/vapHz6KOb2wVQzVeeQKzjoGFILJLE1IDEtuAxJCekYP2dY/C382Unnd2XH+nEjCmBsyvZTL1f2bb7RrajckwR/5iYoLmUUVooxrgSl2c8AACGAiz/NYsb94Q2/Kx7utZYq6fc4oMcnW4XofVNZLtBhGU3QMEU0fzY9UtoZCCfzVCCUlyP4sC4mLYLnj06UObVNRfCUef8TkFN/6a7uofoZNylvdsCvPaqxJUe3IX6MzSQ6yYP3YlgAgiggO1Je9H2j4XM9Y4MGi0UQ0qcvJLIDE1ZLwwruc0DCIP8lVsL2UirdFpMciLrH2BcalrVGe114HmUwOV6gwG6IcUIJoMBkia0Dn7Tsey64qLimjhyyAiGGk1Etnk8ZV4BIi35XZj0ScADymkVCVng+/Y539oNg=

matrix:
  include:
    - sudo: required
      env: TARGET=x86_64-unknown-linux-gnu
      services:
        - docker
    - os: osx
      osx_image: xcode9.3beta
      env: TARGET=x86_64-apple-darwin TRAVIS_PYTHON_VERSION=2.7.14 RELEASE_PYTHON_VERSION=-cp27
      sudo: required
    - os: osx
      osx_image: xcode9.3beta
      env: TARGET=x86_64-apple-darwin TRAVIS_PYTHON_VERSION=3.6.5 RELEASE_PYTHON_VERSION=-cp36
      sudo: required

before_install:
  - echo $LATEST_TAG > key.txt
  - echo $PRE_CMD
  - bash ci/pre_install.sh

install:
  - bash ci/install.sh

cache: pip

script:
  - bash ci/script.sh
  # only run coverage reporting on OS X
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      source venv/bin/activate;
      python setup.py build_ext --inplace;
      nosetests --with-coverage --cover-package $PROJECT_NAME;
    fi

branches:
  only:
    - master

after_success:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      source venv/bin/activate;
      coveralls;
    fi

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  # TODO Regenerate this api_key for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Call `travis encrypt $github_token` where $github_token is the token you got in the previous
  # step and `travis` is the official Travis CI gem (see https://rubygems.org/gems/travis/)
  # - Enter the "encrypted value" below
  api_key:
        - secure: ZlP5QnHGAQzTdYyRXSwPoMXqEM6SKP9kVNd+NjpAzx8yWq75t5dRNbM4tpLx95vVEAseiJp69CzRrVgg/CjG796JByKZBklrUkT6gGbBpcfq81u/M7dpc+xJ3uAupom96zMtzaEP2C2/y9uIOGkL+FH6s1AB7dvf/qXQL7dYBPCRytXEdYNJcuF0dbOESduZNunaxg4tgAMNDc5syPsc8qMag+JxmUwNvlUHuuS6dCijCIVMNHIpghoMxh+WAQoV4K9dbfsgM/+k1CfZhnhfssiUJii3tc/UbvGbnTIU1Ku1iuZNJwiF6NwOWcwGC8d2AkdPXoT2YFNI6ElQ76YizFakx92INaqi6w/lrzdytVWt/Jg2m0R4+HOE6T+jlwccwCQgo0mPVTGO0oCPCxstJOLitq/+RP2YUpxcj0lw5i0kTGWlueGzdWwTqfTLmY+nb/wRhNH0n5K0Jtwqy6ktYyDrd1ov5Ksa6hUWScEJsejfSxwYO2iC6KBP85Q6p580On1B8KLkld6SmiyOT+mYaxsLsqOb1ycPnwU+vZxcSAB9+IxStnfPtaxu6ovvF+IWzwb/ZOP1TjH6uat6ES/reER83h/dNWSXYlIzVf3HwhkEcMD9Mpe+ZOIk7g+7kfKruxnZ8537PdTbx0HpR5vG3mtR6jgQ11TvFEjwQsviPDs=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}${RELEASE_PYTHON_VERSION}.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    tags: true

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
